name: KansasCityOhm
favicon: null
layout_spectrum: 0.8937110325787216
typography_spectrum: 0.7717178899329156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7655213628895581
  lightness: 0.5290243576746434
  saturation: 0.03640803275629878
  rhythmicContrast: 0.42123141163028777
purpose: []
